[package]
name = "trylock"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
tokio = { version = "1.8.4", features = ["sync"] }
futures = "0.3.6"
lazy_static = "1.4.0"
